export const SITE_NAME = '빅데이터 마케팅 랩'
export const SITE_NAME_EN = 'BDM Lab'
export const SITE_URL = 'https://bigdatamarketinglab.com'
export const SITE_DESCRIPTION = '데이터와 연구 기반의 마케팅 분석. 감 대신 근거.'
export const AUTHOR_NAME = '임보람'
export const INSTAGRAM_HANDLE = '@bdm.lab'
export const INSTAGRAM_URL = 'https://instagram.com/bdm.lab'
