export const SITE_NAME = '빅데이터마케팅 랩'
export const SITE_NAME_EN = 'BDM Lab'
export const SITE_URL = 'https://bigdatamarketinglab.com'
export const SITE_DESCRIPTION = '직감 대신 근거. 데이터로 읽는 마케팅.'
export const AUTHOR_NAME = '임보람'
export const INSTAGRAM_HANDLE = '@bdm.lab'
export const INSTAGRAM_URL = 'https://instagram.com/bdm.lab'
export const CONTACT_EMAIL = 'contact@bigdatamarketinglab.com'
